### ISSUE TITLE
Decimal delimiter inconsistent

### ISSUE THREAD

**Issue by ordo01** [suaveolent/ha-hoymiles-wifi#35]
Hi,
please check and correct the usage of decimal delimiters. Currently it is a mix of "." and "," for the inverter. See the attached screenshot.
For most of the values a comma is used but for the total energy a dot is used as decimal delimiter. At least if the total DC energy is below 1 kWh. 

![Screenshot from 2024-05-03 12-56-18](https://github.com/suaveolent/ha-hoymiles-wifi/assets/19726406/c06385f5-2a96-46c0-bc51-eefd2999a7e9)

**Comment by suaveolent** [comment]
Thanks, however I think this is Home Assistant/region specific. 

The "," is the comma separator, the "." the thoundsands separator. 

For example, in my Home Assistant the values are reversed, since I am using a different locale.

The Port DC total energy is actually 77 thousand Watt hours. (77kWh)
