### ISSUE TITLE
Suppress state changes when DTU goes offline

### ISSUE THREAD

**Issue by sc-ampersand-p** [suaveolent/ha-hoymiles-wifi#44]
I find it strange that, when the DTU goes offline because the inverter switches off, some entities change their state. I understand that this is what the DTU is reporting, but from a user point of view, the entity changes are suggesting changes that aren't happening. 

Considering the fact that the Power Limiting feature is not safe to use, I was a bit alarmed the state allegedly changed multiple times per day (cloudy, so the inverter went offline multiple times): 

<img src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/63103291/53021df0-eb68-42f5-81f3-6ca063ea4d3c" width="120">

What's downright false, but less concerning, is the version info for both the inverter's hardware and software: 
<img src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/63103291/8318a065-bf92-45f3-818b-537536e2642f" width="120">
<img src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/63103291/9ef9ce1c-faf5-46df-b97b-ea95a41f80f4" width="120">

What I also find strange is that the DTU signal strength allegedly never changes, even though the DTU clearly was offline in the corresponding time frame: 
<img src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/63103291/9e836240-e806-4139-9beb-acf5e1e09db1" width="120">

Making some changes here would clearly be in the "nice to have" category, maybe with the power limiter as the single exception. So not urgent or critical by any means.

Happy to discuss 😊

**Comment by suaveolent** [comment]
Thanks, that indeed already on my to do list, since it bugs me myself.

**Comment by suaveolent** [comment]
@sc-ampersand-p I have just released a pre-release version  (`0.2.4-dev`) which should cope with the version string. (It will just keep showing the same version, even though the inverter is offline).

As far as the signal strengh goes, I try to not immediately set the signal strength to 0 if the inverter cannot be reached for a couple of minutes, as inverters with blocked Internet access also cannot be reached sometimes.

Otherwise, the value is the one reported by the DTU. 
In the night, the value should drop to 0.

**Comment by suaveolent** [comment]
Implemented in `v0.2.4`
